### PR TITLE
replaced default python pictures with avatar pics

### PR DESCRIPTION
**Pull request by liamosaur**

### CODE REVIEW

**Comment by glasnt** [comment]
Hi @liamosaur! It looks like you're wanting to change your own avatar. That's cool. 

But if I could get confirmation from "Alex" that this is indeed the avatar they want, that'd be amazing.

**Comment by mangodotpdf** [comment]
Hi @glasnt I am 100% on board with my lime avatar, thanks @liamosaur

**Comment by glasnt** [comment]
@liamosaur ಠ_ಠ

**Comment by liamosaur** [comment]
Organising cons is stressful enough without shenanigans, so with hindsight, that was kind of mean and I apologise. No more tomfoolery 🙈

**Pull request merged**
